### ISSUE TITLE
Tutorial bug:  The process cannot access the file because it is being used by another process

### ISSUE THREAD

**Issue by xy103** [brainglobe/bg-atlasapi#112]
Hi I'm trying to run the tutorial for brainreg and kept getting the following error. Could someone take a look and help? Thanks!

Traceback (most recent call last):
  File "C:\Users\xinto\anaconda3\envs\brainreg_env\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\xinto\anaconda3\envs\brainreg_env\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\xinto\anaconda3\envs\brainreg_env\Scripts\brainreg.exe\__main__.py", line 7, in <module>
  File "C:\Users\xinto\anaconda3\envs\brainreg_env\lib\site-packages\brainreg\cli.py", line 207, in main
    register(
  File "C:\Users\xinto\anaconda3\envs\brainreg_env\lib\site-packages\brainreg\main.py", line 65, in main
    run_niftyreg(
  File "C:\Users\xinto\anaconda3\envs\brainreg_env\lib\site-packages\brainreg\backend\niftyreg\run.py", line 214, in run_niftyreg
    delete_directory_contents(niftyreg_directory)
  File "C:\Users\xinto\anaconda3\envs\brainreg_env\lib\site-packages\imlib\general\system.py", line 351, in delete_directory_contents
    os.remove(os.path.join(directory, f))
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\xinto\\Desktop\\test_brain\\output\\niftyreg\\deformation_field.nii'

**Comment by xy103** [comment]
Hi,

No other process is accessing these files though. I’ve tried it multiple
times and it seems like some code within the brainreg package is not
closing things properly when they’re done running.

**Comment by FedeClaudi** [comment]
If it's a brainreg issue, then @adamltyson  would be the best person to help you.
Can you give us more details on how are you running the code and exactly what code? Also please some info like operating system, python version...

**Comment by xy103** [comment]
Hi I'm doing exactly what's outlined here(
https://docs.brainglobe.info/brainreg/tutorial)  in the tutorial on a
windows 10 machine inside a virtual environment. Python version Python
3.9.7. This issue occurs in cmd and powershell.

**Comment by FedeClaudi** [comment]
Thanks for the info. If you don't have the file/directory open in something else then perhaps it is `brainreg`'s fault. Let's see what @adamltyson  says!
